[package]
edition.workspace = true
name = "proxy"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
httparse.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true