OUTPUT := "build"

dbg:
    meson setup {{OUTPUT}}/dbg --reconfigure -Dbuildtype=debug -Db_sanitize=address -Db_lundef=false
    meson compile -C {{OUTPUT}}/dbg    
    ln -sf {{OUTPUT}}/dbg/compile_commands.json .

release:
    meson setup {{OUTPUT}}/rel -Dbuildtype=release -Db_lto=true
    meson compile -C {{OUTPUT}}/rel

