
[workspace]
members = ["proxy", "sserver"]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
httparse = "1.9"
mimalloc = "0.1"
mio = { version = "1.0", features = ["log", "net"] }
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = 'thin'
opt-level = 3
overflow-checks = false
panic = 'unwind'
rpath = false

# cargo build --profile release-lto
[profile.release-lto]
inherits = "release"
lto = true
panic = "abort"
strip = "debuginfo"
