debug:
    zig build -Doptimize=Debug --prefix target/debug

release:
	zig build --release=safe -Doptimize=ReleaseSafe --prefix target/release

run_debug: debug
    ./target/debug/bin/sserver --port 10010

run: release
    ./target/release/bin/sserver --port 10010
