name: c

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: RelWithDebInfo
  OPT: ReleaseSafe

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./c

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - uses: mlugg/setup-zig@v1

      - name: Build by zig
        run: zig build --verbose --summary all --release=safe -Doptimize=${{env.OPT}} --prefix target
