name: cross build c

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./c

    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Build by zig
        run: zig build --verbose --summary all --release=safe -Doptimize=ReleaseFast --prefix target
