name: c

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: RelWithDebInfo
  OPT: ReleaseSafe

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./c

    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: pip3 install -U meson -U ninja

      - name: setup
        run: meson setup target -Dbuildtype=release -Db_lto=true

      - name: build by meson
        run: meson compile -C target

      # - uses: mlugg/setup-zig@v2
      # with:
      # version: 0.14.1

      # - name: build by zig
      # run: zig build --verbose --summary all --release=safe -Doptimize=ReleaseFast --prefix target
