name: zig

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./zig

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build
        run: zig build --release=safe -Doptimize=ReleaseSafe --prefix target
